<?php

namespace AppBundle\Repository;

/**
 * GroupingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupingRepository extends \Doctrine\ORM\EntityRepository
{
}
